/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Configuration settings for users and organizations on Sourcegraph.
 */
export interface Settings {
  experimentalFeatures?: SettingsExperimentalFeatures;
  openInEditor?: SettingsOpenInEditor;
  /**
   * Predefined search snippets that can be appended to any search (also known as search scopes)
   */
  "search.scopes"?: SearchScope[];
  /**
   * Never fall back to search-based code intelligence.
   */
  "codeIntel.disableSearchBased"?: boolean;
  /**
   * Whether to enable trace logging on the extension.
   */
  "codeIntel.traceExtension"?: boolean;
  /**
   * Whether to fetch multiple precise definitions and references on hover.
   */
  "codeIntel.disableRangeQueries"?: boolean;
  /**
   * Whether to supplement precise references with search-based results.
   */
  "codeIntel.mixPreciseAndSearchBasedReferences"?: boolean;
  /**
   * Whether to include forked repositories in search results.
   */
  "basicCodeIntel.includeForks"?: boolean;
  /**
   * Whether to include archived repositories in search results.
   */
  "basicCodeIntel.includeArchives"?: boolean;
  /**
   * Whether to run global searches over all repositories. On instances with many repositories, this can lead to issues such as: low quality results, slow response times, or significant load on the Sourcegraph instance. Defaults to true.
   */
  "basicCodeIntel.globalSearchesEnabled"?: boolean;
  /**
   * Whether to use only indexed requests to the search API.
   */
  "basicCodeIntel.indexOnly"?: boolean;
  /**
   * The timeout (in milliseconds) for un-indexed search requests.
   */
  "basicCodeIntel.unindexedSearchTimeout"?: number;
  /**
   * The default number of lines to show as context below and above search results. Default is 1.
   */
  "search.contextLines"?: number;
  /**
   * DEPRECATED: this setting is no longer read when the default 'keyword' patterntype is enabled, which always uses the 'precise' mode. Smart search will be removed in a future release.
   */
  "search.defaultMode"?: string;
  /**
   * The default pattern type that search queries will be interpreted as.
   */
  "search.defaultPatternType"?: string;
  /**
   * Whether query patterns are treated case sensitively. Patterns are case insensitive by default.
   */
  "search.defaultCaseSensitive"?: boolean;
  /**
   * The number of results we send down during a search. Note: this is different to the count: in the query. The search will continue once we hit displayLimit and updated filters and statistics will continue to stream down. Defaults to 1500.
   */
  "search.displayLimit"?: number;
  /**
   * Whether searches should include searching forked repositories.
   */
  "search.includeForks"?: boolean;
  /**
   * Whether searches should include searching archived repositories.
   */
  "search.includeArchived"?: boolean;
  /**
   * DEPRECATED: This setting will be removed in a future version of Sourcegraph.
   */
  quicklinks?: QuickLink[];
  /**
   * Whether the sidebar on the repo view should be open by default.
   */
  fileSidebarVisibleByDefault?: boolean;
  /**
   * DEPRECATED: Use `notices` instead.
   *
   * An array (often with just one element) of messages to display at the top of all pages, including for unauthenticated users. Users may dismiss a message (and any message with the same string value will remain dismissed for the user).
   *
   * Markdown formatting is supported.
   *
   * Usually this setting is used in global and organization settings. If set in user settings, the message will only be displayed to that user. (This is useful for testing the correctness of the message's Markdown formatting.)
   *
   * MOTD stands for "message of the day" (which is the conventional Unix name for this type of message).
   */
  motd?: string[];
  /**
   * Show absolute timestamps in the history panel and only show relative timestamps (e.g.: "5 days ago") in tooltip when hovering.
   */
  "history.preferAbsoluteTimestamps"?: boolean;
  /**
   * Custom page size for the history tab. If set, the history tab will populate that number of commits the first time the history tab is opened and then double the number of commits progressively.
   */
  "history.defaultPageSize"?: number;
  /**
   * Custom informational messages to display to users at specific locations in the Sourcegraph user interface.
   *
   * Usually this setting is used in global and organization settings. If set in user settings, the message will only be displayed to that single user.
   */
  notices?: Notice[];
  /**
   * Whether to show alerts for patch version updates. Alerts for major and minor version updates will be shown if `alerts.showMajorMinorUpdatess` is true.
   */
  "alerts.showPatchUpdates"?: boolean;
  /**
   * Whether to show alerts for major and minor version updates. Alerts for patch version updates will be shown if `alerts.showPatchUpdates` is true.
   */
  "alerts.showMajorMinorUpdates"?: boolean;
  /**
   * Disables observability-related site alert banners.
   */
  "alerts.hideObservabilitySiteAlerts"?: boolean;
  /**
   * Disable search suggestions below the search bar when constructing queries. Defaults to false.
   */
  "search.hideSuggestions"?: boolean;
  /**
   * The number of seconds to execute the aggregation for when running in extended timeout mode. This value should always be less than any proxy timeout if one exists. The maximum value is equal to searchLimits.maxTimeoutSeconds
   */
  "insights.aggregations.extendedTimeout"?: number;
  /**
   * Key-value pairs of code host URLs to Swarm URLs. Keys should have no prefix and should not end with a slash, like "perforce.company.com:1666". Values should look like "https://swarm.company.com/", with a slash at the end.
   */
  "perforce.codeHostToSwarmMap"?: {
    [k: string]: string;
  };
  /**
   * If enabled, all members of the org will be treated as admins (e.g. can edit, apply, delete) for all batch changes created in that org.
   */
  "orgs.allMembersBatchChangesAdmin"?: boolean;
  [k: string]: unknown;
}
/**
 * Experimental features and settings.
 */
export interface SettingsExperimentalFeatures {
  /**
   * Enables new experimental search results filters panel
   */
  newSearchResultFiltersPanel?: boolean;
  /**
   * Enables new experimental search UI navigation
   */
  newSearchNavigationUI?: boolean;
  /**
   * Enables new experimental search results UI, such as preview panel feature and updated search and filter layouts.
   */
  newSearchResultsUI?: boolean;
  /**
   * Specifies which (code insight repo) editor to use for repo query UI
   */
  codeInsightsRepoUI?: "old-strict-list" | "single-search-query" | "search-query-or-strict-list";
  /**
   * DEPRECATED: This feature is now permanently enabled. Enables query based search contexts
   */
  searchContextsQuery?: boolean;
  /**
   * Enables fuzzy finder with the keyboard shortcut `Cmd+K` on macOS and `Ctrl+K` on Linux/Windows.
   */
  fuzzyFinder?: boolean;
  /**
   * Enables the 'Fuzzy finder' action in the global navigation bar
   */
  fuzzyFinderNavbar?: boolean;
  /**
   * Enables the 'All' tab of the fuzzy finder
   */
  fuzzyFinderAll?: boolean;
  /**
   * Enables the 'Actions' tab of the fuzzy finder
   */
  fuzzyFinderActions?: boolean;
  /**
   * Enables the 'Repositories' tab of the fuzzy finder
   */
  fuzzyFinderRepositories?: boolean;
  /**
   * Enables the 'Symbols' tab of the fuzzy finder
   */
  fuzzyFinderSymbols?: boolean;
  /**
   * The maximum number of files a repo can have to use case-insensitive fuzzy finding
   */
  fuzzyFinderCaseInsensitiveFileCountThreshold?: number;
  /**
   * Enables/disables the Batch Changes server side execution feature.
   */
  batchChangesExecution?: boolean;
  /**
   * How to rank search results in the client
   */
  clientSearchResultRanking?: string;
  /**
   * Shows code monitor webhook and Slack webhook actions in the UI, allowing users to configure them.
   */
  codeMonitoringWebHooks?: boolean;
  /**
   * Shows code monitoring logs tab.
   */
  showCodeMonitoringLogs?: boolean;
  /**
   * Shows a panel with code insights templates for go code checker results.
   */
  goCodeCheckerTemplates?: boolean;
  /**
   * Enables Compute powered Code Insights
   */
  codeInsightsCompute?: boolean;
  /**
   * Fetch un-highlighted blob contents to render immediately, decorate with syntax highlighting once loaded.
   */
  enableLazyBlobSyntaxHighlighting?: boolean;
  /**
   * Pre-fetch plaintext file revisions from sidebar on hover/focus.
   */
  enableSidebarFilePrefetch?: boolean;
  /**
   * Pre-fetch plaintext file revisions from search results on hover/focus.
   */
  enableSearchFilePrefetch?: boolean;
  /**
   * Fetch un-highlighted file result contents to render immediately, decorate with syntax highlighting once loaded.
   */
  enableLazyFileResultSyntaxHighlighting?: boolean;
  /**
   * Display aggregations for your search results on the search screen.
   */
  searchResultsAggregations?: boolean;
  /**
   * Search results aggregations are triggered automatically with a search.
   */
  proactiveSearchResultsAggregations?: boolean;
  /**
   * Show the initial letter of the symbol kind instead of icons.
   */
  symbolKindTags?: boolean;
  /**
   * Specify which version of the search query input to use
   */
  searchQueryInput?: "v1" | "v2";
  /**
   * DEPRECATED: this setting is no longer used. To disable keyword search, set `search.defaultPatternType: standard` instead.
   */
  keywordSearch?: boolean;
  [k: string]: unknown;
}
/**
 * Group of settings related to opening files in an editor.
 */
export interface SettingsOpenInEditor {
  /**
   * The editor to open files in. If set to this to "custom", you must also set "custom.urlPattern"
   */
  editorIds?: (
    | "appcode"
    | "atom"
    | "clion"
    | "goland"
    | "idea"
    | "phpstorm"
    | "pycharm"
    | "rider"
    | "rubymine"
    | "sublime"
    | "vscode"
    | "webstorm"
    | "custom"
  )[];
  /**
   * The absolute path on your computer where your git repositories live. All git repos to open have to be cloned under this path with their original names. "/Users/yourusername/src" is a valid absolute path, "~/src" is not. Works both with and without a trailing slash.
   */
  "projectPaths.default"?: string;
  /**
   * Overrides the default path when the browser detects Linux. Works both with and without a trailing slash.
   */
  "projectPaths.linux"?: string;
  /**
   * Overrides the default path when the browser detects macOS. Works both with and without a trailing slash.
   */
  "projectPaths.mac"?: string;
  /**
   * Overrides the default path when the browser detects Windows. Doesn't need a trailing backslash.
   */
  "projectPaths.windows"?: string;
  /**
   * Each key will be replaced by the corresponding value in the final URL. Keys are regular expressions, values can contain backreferences ($1, $2, ...).
   */
  replacements?: {
    /**
     * Replace string. For backreferences to capturing groups, use $1, $2, ...
     */
    [k: string]: string;
  };
  /**
   * Forces using protocol handlers (like ikea://open?file=...) or the built-in REST API (http://localhost:63342/api/file...). If omitted, protocol handlers are used if available, otherwise the built-in REST API is used.
   */
  "jetbrains.forceApi"?: "protocolHandler" | "builtInServer";
  /**
   * Indicates that the given project path is a UNC (Universal Naming Convention) path.
   */
  "vscode.isProjectPathUNCPath"?: boolean;
  /**
   * If set, files will open in VS Code Insiders rather than VS Code.
   */
  "vscode.useInsiders"?: boolean;
  /**
   * If set, files will open on a remote server via SSH. This requires vscode.remoteHostForSSH to be specified and VS Code extension "Remote Development by Microsoft" installed in your VS Code.
   */
  "vscode.useSSH"?: boolean;
  /**
   * The remote host as "USER@HOSTNAME". This needs you to install the extension called "Remote Development by Microsoft" in your VS Code.
   */
  "vscode.remoteHostForSSH"?: string;
  /**
   * If you add "custom" to openineditor.editorIds, this must be set. Use the placeholders "%file", "%line", and "%col" to mark where the file path, line number, and column number must be insterted. Example URL for IntelliJ IDEA: "idea://open?file=%file&line=%line&column=%col"
   */
  "custom.urlPattern"?: string;
}
export interface SearchScope {
  /**
   * The human-readable name for this search scope
   */
  name: string;
  /**
   * The query string of this search scope
   */
  value: string;
}
export interface QuickLink {
  /**
   * The human-readable name for this quick link
   */
  name: string;
  /**
   * The URL of this quick link (absolute or relative)
   */
  url: string;
  /**
   * A description for this quick link
   */
  description?: string;
}
export interface Notice {
  /**
   * The message to display. Markdown formatting is supported.
   */
  message: string;
  /**
   * The location where this notice is shown: "top" for the top of every page, "home" for the homepage.
   */
  location: "top" | "home";
  variant?: "primary" | "secondary" | "success" | "danger" | "warning" | "info" | "note";
  /**
   * Whether this notice can be dismissed (closed) by the user.
   */
  dismissible?: boolean;
  /**
   * Overrides for the notice's default style. You probably want to use notice 'variant' setting instead.
   */
  styleOverrides?: {
    /**
     * The hex code of the background color for this notice.
     */
    backgroundColor?: string;
    /**
     * The hex code of the text color for this notice.
     */
    textColor?: string;
    /**
     * Whether the notice text should be centered.
     */
    textCentered?: boolean;
    [k: string]: unknown;
  };
}
