// Generated by Wrangler by running `wrangler types`

interface Env {
  KV_STORAGE: string;
  SESSION_JWT_SECRET: string;
  ACTOR_KIT_HOST: string;
  ACTOR_KIT_SECRET: string;
  NODE_ENV: string;
  REMIX: DurableObjectNamespace /* Remix */;
  USER: DurableObjectNamespace /* User */;
  SCENARIO: DurableObjectNamespace /* Scenario */;
}
