#:schema node_modules/wrangler/config-schema.json
name = "ui-labs"
main = "dist/index.js"
compatibility_date = "2024-09-25"

assets = { directory = "./public" }

[define]
"process.env.REMIX_DEV_ORIGIN" = "'http://127.0.0.1:8002'"
"process.env.REMIX_DEV_SERVER_WS_PORT" = "8002"

[vars]
ACTOR_KIT_HOST = "ui-labs.peterjaberau.dev"

[[durable_objects.bindings]]
name = "REMIX"
class_name = "Remix"

[[durable_objects.bindings]]
name = "USER"
class_name = "User"

[[durable_objects.bindings]]
name = "SCENARIO"
class_name = "Scenario"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Remix", "User", "Scenario"]

[observability]
enabled = true
